// Auto-generated. Do not edit!

// (in-package lab7.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class PumaGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.puma_id = null;
    }
    else {
      if (initObj.hasOwnProperty('puma_id')) {
        this.puma_id = initObj.puma_id
      }
      else {
        this.puma_id = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type PumaGoal
    // Serialize message field [puma_id]
    bufferOffset = _serializer.uint32(obj.puma_id, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type PumaGoal
    let len;
    let data = new PumaGoal(null);
    // Deserialize message field [puma_id]
    data.puma_id = _deserializer.uint32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 4;
  }

  static datatype() {
    // Returns string type for a message object
    return 'lab7/PumaGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'b4fa702367b37c100fd7fe6f32c2dc28';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # goal
    uint32 puma_id
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new PumaGoal(null);
    if (msg.puma_id !== undefined) {
      resolved.puma_id = msg.puma_id;
    }
    else {
      resolved.puma_id = 0
    }

    return resolved;
    }
};

module.exports = PumaGoal;
