// Generated by gencpp from file lab7/PumaGoal.msg
// DO NOT EDIT!


#ifndef LAB7_MESSAGE_PUMAGOAL_H
#define LAB7_MESSAGE_PUMAGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace lab7
{
template <class ContainerAllocator>
struct PumaGoal_
{
  typedef PumaGoal_<ContainerAllocator> Type;

  PumaGoal_()
    : puma_id(0)  {
    }
  PumaGoal_(const ContainerAllocator& _alloc)
    : puma_id(0)  {
  (void)_alloc;
    }



   typedef uint32_t _puma_id_type;
  _puma_id_type puma_id;





  typedef boost::shared_ptr< ::lab7::PumaGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::lab7::PumaGoal_<ContainerAllocator> const> ConstPtr;

}; // struct PumaGoal_

typedef ::lab7::PumaGoal_<std::allocator<void> > PumaGoal;

typedef boost::shared_ptr< ::lab7::PumaGoal > PumaGoalPtr;
typedef boost::shared_ptr< ::lab7::PumaGoal const> PumaGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::lab7::PumaGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::lab7::PumaGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace lab7

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'visualization_msgs': ['/opt/ros/kinetic/share/visualization_msgs/cmake/../msg'], 'lab7': ['/nfshome/gat7hb/catkin_ws/devel/share/lab7/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::lab7::PumaGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::lab7::PumaGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab7::PumaGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::lab7::PumaGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab7::PumaGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::lab7::PumaGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::lab7::PumaGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4fa702367b37c100fd7fe6f32c2dc28";
  }

  static const char* value(const ::lab7::PumaGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4fa702367b37c10ULL;
  static const uint64_t static_value2 = 0x0fd7fe6f32c2dc28ULL;
};

template<class ContainerAllocator>
struct DataType< ::lab7::PumaGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "lab7/PumaGoal";
  }

  static const char* value(const ::lab7::PumaGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::lab7::PumaGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# goal\n\
uint32 puma_id\n\
";
  }

  static const char* value(const ::lab7::PumaGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::lab7::PumaGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.puma_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PumaGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::lab7::PumaGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::lab7::PumaGoal_<ContainerAllocator>& v)
  {
    s << indent << "puma_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.puma_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LAB7_MESSAGE_PUMAGOAL_H
