(cl:defpackage lab7-msg
  (:use )
  (:export
   "<PUMAACTION>"
   "PUMAACTION"
   "<PUMAACTIONFEEDBACK>"
   "PUMAACTIONFEEDBACK"
   "<PUMAACTIONGOAL>"
   "PUMAACTIONGOAL"
   "<PUMAACTIONRESULT>"
   "PUMAACTIONRESULT"
   "<PUMAFEEDBACK>"
   "PUMAFEEDBACK"
   "<PUMAGOAL>"
   "PUMAGOAL"
   "<PUMARESULT>"
   "PUMARESULT"
  ))

