; Auto-generated. Do not edit!


(cl:in-package lab7-msg)


;//! \htmlinclude PumaActionGoal.msg.html

(cl:defclass <PumaActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type lab7-msg:PumaGoal
    :initform (cl:make-instance 'lab7-msg:PumaGoal)))
)

(cl:defclass PumaActionGoal (<PumaActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PumaActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PumaActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name lab7-msg:<PumaActionGoal> is deprecated: use lab7-msg:PumaActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <PumaActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lab7-msg:header-val is deprecated.  Use lab7-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <PumaActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lab7-msg:goal_id-val is deprecated.  Use lab7-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <PumaActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lab7-msg:goal-val is deprecated.  Use lab7-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PumaActionGoal>) ostream)
  "Serializes a message object of type '<PumaActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PumaActionGoal>) istream)
  "Deserializes a message object of type '<PumaActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PumaActionGoal>)))
  "Returns string type for a message object of type '<PumaActionGoal>"
  "lab7/PumaActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PumaActionGoal)))
  "Returns string type for a message object of type 'PumaActionGoal"
  "lab7/PumaActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PumaActionGoal>)))
  "Returns md5sum for a message object of type '<PumaActionGoal>"
  "29748ab911deec3edd6aa53f1e4c97f3")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PumaActionGoal)))
  "Returns md5sum for a message object of type 'PumaActionGoal"
  "29748ab911deec3edd6aa53f1e4c97f3")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PumaActionGoal>)))
  "Returns full string definition for message of type '<PumaActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%PumaGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: lab7/PumaGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%uint32 puma_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PumaActionGoal)))
  "Returns full string definition for message of type 'PumaActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%PumaGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: lab7/PumaGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%uint32 puma_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PumaActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PumaActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PumaActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
