; Auto-generated. Do not edit!


(cl:in-package lab7-msg)


;//! \htmlinclude PumaGoal.msg.html

(cl:defclass <PumaGoal> (roslisp-msg-protocol:ros-message)
  ((puma_id
    :reader puma_id
    :initarg :puma_id
    :type cl:integer
    :initform 0))
)

(cl:defclass PumaGoal (<PumaGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PumaGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PumaGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name lab7-msg:<PumaGoal> is deprecated: use lab7-msg:PumaGoal instead.")))

(cl:ensure-generic-function 'puma_id-val :lambda-list '(m))
(cl:defmethod puma_id-val ((m <PumaGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader lab7-msg:puma_id-val is deprecated.  Use lab7-msg:puma_id instead.")
  (puma_id m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PumaGoal>) ostream)
  "Serializes a message object of type '<PumaGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'puma_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'puma_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'puma_id)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'puma_id)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PumaGoal>) istream)
  "Deserializes a message object of type '<PumaGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'puma_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) (cl:slot-value msg 'puma_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) (cl:slot-value msg 'puma_id)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) (cl:slot-value msg 'puma_id)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PumaGoal>)))
  "Returns string type for a message object of type '<PumaGoal>"
  "lab7/PumaGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PumaGoal)))
  "Returns string type for a message object of type 'PumaGoal"
  "lab7/PumaGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PumaGoal>)))
  "Returns md5sum for a message object of type '<PumaGoal>"
  "b4fa702367b37c100fd7fe6f32c2dc28")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PumaGoal)))
  "Returns md5sum for a message object of type 'PumaGoal"
  "b4fa702367b37c100fd7fe6f32c2dc28")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PumaGoal>)))
  "Returns full string definition for message of type '<PumaGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%uint32 puma_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PumaGoal)))
  "Returns full string definition for message of type 'PumaGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# goal~%uint32 puma_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PumaGoal>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PumaGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'PumaGoal
    (cl:cons ':puma_id (puma_id msg))
))
