; Auto-generated. Do not edit!


(cl:in-package lab7-msg)


;//! \htmlinclude PumaResult.msg.html

(cl:defclass <PumaResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass PumaResult (<PumaResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PumaResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PumaResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name lab7-msg:<PumaResult> is deprecated: use lab7-msg:PumaResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PumaResult>) ostream)
  "Serializes a message object of type '<PumaResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PumaResult>) istream)
  "Deserializes a message object of type '<PumaResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PumaResult>)))
  "Returns string type for a message object of type '<PumaResult>"
  "lab7/PumaResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PumaResult)))
  "Returns string type for a message object of type 'PumaResult"
  "lab7/PumaResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PumaResult>)))
  "Returns md5sum for a message object of type '<PumaResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PumaResult)))
  "Returns md5sum for a message object of type 'PumaResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PumaResult>)))
  "Returns full string definition for message of type '<PumaResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PumaResult)))
  "Returns full string definition for message of type 'PumaResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PumaResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PumaResult>))
  "Converts a ROS message object to a list"
  (cl:list 'PumaResult
))
